### ISSUE TITLE
Missing coefficient dictionary file

### ISSUE THREAD

**Issue by Noxical** [rdgorman/pneumatic_conveying#1]
Hi, I am reading the program and trying to understand, quite interesting as you have implemented so many methods and sort of fitting tool. 

Is it correct that the coefficient dictionary file is missing in the folder? Can you add example?

Thanks for sharing btw

Regards

**Comment by rdgorman** [comment]
I have published a new version that includes the missing [coefficient dictionary file](https://github.com/rdgorman/pneumatic_conveying/blob/4990f119904045167ee5622f46c7a10b64fd2bfb/Coefficient_Dictionary.csv).

It is used to define the number of coefficients needed for each method that is available. Ultimately, this is how the evolutionary model knows how many coefficients to fit when evaluating an individual that contains that method.
